### ISSUE TITLE
application.get should not support app names

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-sdk#1030]
`application.get()` should not support searching by application name, so that it never returns ambiguous results.
Consumers that care about this use case should be using `application.getAll()`.

Discussed in product call 2021-01-05 as part of the CLI changes with regards to the release of orgs.
See: https://jel.ly.fish/brainstorm-call-product-5jan2021-d6f4871d-c9d9-4deb-82ca-7da2c25034a6

**Comment by pdcastro** [comment]
During the product call, it was suggested that the SDK should not offer `application.get(appName)` because the app name on its own is ambiguous. However, I think that an alternative that would keep with the spirit of the suggestion is for the SDK to require upfront disambiguation in the form of an option that specified the "kind" of application that the caller would like to get: "direct access" (an app that belongs to an org that belongs to the user), "public app" or some other kind. If the app "kind" was not specified, the SDK would throw an error such as "Invalid arguments" (indicating a bug in the caller code, rather than user input ambiguity).

**Comment by thgreasi** [comment]
@pdcastro I think that the point was to just make all app related calls unambiguous, but just teaching the users how to use app slug. This wouldn't just solve the public app issue, but also the ambiguous errors that cli users get when using an app name that is used by more than one directly accessible apps (in different orgs). If we go this way, then it would also simplify the CLI code as well, since it will no longer have to follow any  "ambiguous error => show a list of apps to select" flow.

That's a good reminder though to invite you to the respective call I'm planning about direct pine usage in the CLI & UI.
