### ISSUE TITLE
Version 14 breaks with open-balena

### ISSUE THREAD

**Issue by bartversluijs** [balena-io/balena-sdk#920]
When using balena-sdk 14.0.1, it breaks with `open-balena`. A new version of `open-balena` will probably be launched in the next couple of weeks. But it's worth mentioning that the SDK breaks at this moment.

## Expected Behavior
Getting a device with `balena.models.device.get` should return the device when the UUID is given.

## Actual Behavior
Crashes with a 404 on endpoint `/v6/devices`

## Steps to Reproduce the Problem
1. Start open-balena instance
2. Set balena-sdk to that open-balena instance
3. Use function `balena.models.device.get`
4. Results in crash

## Specifications

- SDK version: 14.0.1
- Browser: Insomnia
- Node version: v14.3.0
- Npm version: 6.14.5
- OS: macOS 10.15.4

**Comment by thgreasi** [comment]
Hi @bartversluijs ,

It's true that the at this point the currently latest version of the open-balena-api doesn't offer the `/v6` model endpoint, and as a result the balena-sdk v14 can't work with it.
We recently did quite a big change in our balenaCloud API `/v6` model and we are actively working on also making part of the next open-balena-api version.

At the moment I can only suggest you to stick with the v13 major release of the balena-sdk.
I've opened an open-balena-api issue about this, so that you can track progress:
https://github.com/balena-io/open-balena-api/issues/388

We will let you know once the new open-balena-api version gets released.

Kind regards,
Thodoris

**Comment by bartversluijs** [comment]
I can confirm this is fixed. See https://github.com/balena-io/open-balena-api/pull/483.
