### ISSUE TITLE
If public urls are disabled, hasDeviceUrl(uuid) doesn't return a boolean value

### ISSUE THREAD

**Issue by StefKors** [balena-io/balena-sdk#986]
## Expected Behavior
It's expected that ` balena.models.device.hasDeviceUrl(uuid)` should always return a boolean value.

## Actual Behavior
If public urls are disabled, `balena.models.device.hasDeviceUrl(uuid)` doesn't return a boolean value, but instead returns an error.

## Steps to Reproduce the Problem

1. disable the public url for the device
1. use the node-sdk to run `hasDeviceUrl(uuid)`
1. error is thrown

**Comment by thgreasi** [comment]
I'm pretty sure that this was never the case since we have tests cases for this and I just tried it on my side and wan't able to reproduce.
See: https://github.com/balena-io/balena-sdk/blob/bac5f0e69c2049f84b131e72e6016ee6467a0eb6/tests/integration/models/device.spec.js#L879-L923

The only case that I could guess that this might throw an error (other than connectivity issues and internal server errors) would be if this was run against openBalena, which doesn't support public device urls.
